version: '3.8'

services:
  backend:
    image: node:20
    container_name: blitz-backend
    ports:
      - "5000:5000"   # Exposes the app on port 5000
    working_dir: /app
    volumes:
      - .:/app      # Mounts the current directory to the container
    environment:
      - NODE_ENV=production
    command: ["node", "--watch", "src/server.js"]
    restart: always
    depends_on:
      - db
  
  db:
    image: nouchka/sqlite3
    container_name: sqlite-db
    volumes:
      - ./database.db:/app/database.db   # Mounts your SQLite DB file
    restart: always
